# Generated by Django 4.2.3 on 2023-07-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(blank=True, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=100)),
                ('photo', models.ImageField(blank=True, default=False, upload_to='todo/files/photos/')),
                ('file', models.FileField(blank=True, default=False, upload_to='todo/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Memo', models.TextField(blank=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('Important', models.BooleanField(default=False)),
                ('file', models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='todo.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
