# Generated by Django 4.2.3 on 2023-07-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='todo/files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(blank=True, upload_to='todo/files/photos/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo.file'),
        ),
    ]
