# Generated by Django 3.1.2 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
